package com.tarterware.roadrunner.configs;

import java.util.HashMap;
import java.util.Map;

import org.apache.kafka.clients.admin.AdminClient;
import org.apache.kafka.clients.admin.AdminClientConfig;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Spring configuration class for Kafka-related infrastructure.
 * <p>
 * This class provides the necessary beans to interact with the Kafka cluster
 * for administrative purposes, specifically supporting the cleanup of unique
 * consumer groups generated by application instances.
 * </p>
 */
@Configuration
public class KafkaConfig
{
    /**
     * The address of the Kafka bootstrap servers, injected from the application
     * properties.
     */
    @Value("${spring.kafka.bootstrap-servers}")
    private String bootstrapServers;

    /**
     * Creates and configures a Kafka {@link AdminClient} bean.
     * <p>
     * The AdminClient is used by the application to programmatically manage
     * consumer groups. In a Kubernetes environment, this allows each pod to delete
     * its unique consumer group upon shutdown to prevent cluttering the Kafka
     * cluster with dead consumer groups.
     * </p>
     * * @return a configured {@link AdminClient} instance connected to the
     * specified bootstrap servers.
     * 
     * @see AdminClient
     */
    @Bean
    AdminClient adminClient()
    {
        Map<String, Object> configs = new HashMap<>();
        configs.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
        return AdminClient.create(configs);
    }
}