spring.config.import=optional:secrets.properties

spring.data.rest.base-path=/

mapbox.api.url=https://api.mapbox.com/

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

com.tarterware.redis.host=127.0.0.1

com.tarterware.redis.port=6379

com.tarterware.roadrunner.vehicle-update-period=250ms

com.tarterware.roadrunner.jitter-stat-capacity=200

spring.profiles.active=dev

roadrunner.messaging.redis.enabled=true
roadrunner.messaging.kafka.enabled=false

# Settings for updating the Kubernetes secret
prometheus.secret.namespace=roadrunner
prometheus.secret.name=prometheus-token-secret

# Uncomment to display updateVehicle execution statistics in log.
# logging.level.com.tarterware.roadrunner.components.VehicleManager=DEBUG

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=roadrunner-debug-consumer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.tarterware.roadrunner.*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.tarterware.roadrunner.messaging.VehiclePositionEvent

roadrunner.kafka.topic.vehicle-position=vehicle.position.v1
