spring.config.import=optional:secrets.properties

spring.application.name=roadrunner
spring.data.rest.base-path=/

mapbox.api.url=https://api.mapbox.com/

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

com.tarterware.redis.host=127.0.0.1

com.tarterware.redis.port=6379

com.tarterware.roadrunner.vehicle-update-period=250ms

com.tarterware.roadrunner.jitter-stat-capacity=200

spring.profiles.active=dev

com.tarterware.roadrunner.messaging.kafka.enabled=true

# Enable to display all messages posted to topic
com.tarterware.roadrunner.messaging.kafka.debug.enabled=false

# Settings for updating the Kubernetes secret
prometheus.secret.namespace=roadrunner
prometheus.secret.name=prometheus-token-secret

# Silence these noisy classes.
logging.level.org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer=WARN
logging.level.org.apache.kafka.clients.consumer.internals.SubscriptionState=WARN

# Uncomment to display updateVehicle execution statistics in log.
# logging.level.com.tarterware.roadrunner.components.VehicleManager=DEBUG

# logging.level.com.tarterware.roadrunner.adapters.kafka.KafkaVehicleEventConsumer=DEBUG
# logging.level.com.tarterware.roadrunner.adapters.kafka.KafkaVehicleEventPublisher=DEBUG

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.listener.concurrency=3
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.tarterware.roadrunner.messaging
spring.kafka.consumer.properties.spring.json.use.type.headers=true
spring.kafka.consumer.properties.spring.json.value.default.type=com.tarterware.roadrunner.messaging.VehiclePositionEvent

# Reduce the time the broker waits for a consumer to respond
spring.kafka.consumer.properties.heartbeat.interval.ms=3000
spring.kafka.consumer.properties.session.timeout.ms=10000

com.tarterware.roadrunner.kafka.topic.vehicle-position=vehicle.position.v1
